using Synonms.CarbonBlazor.Icons;

namespace Synonms.CarbonBlazor.Enumerations;

public enum CarbonBlazorIcon
{
    None,
    Add,
    Apps,
    ArrowDownRight,
    ArrowUpRight,
    Building,
    Calendar,
    Cancel,
    CaretDown,
    CaretUp,
    Caution,
    Checkmark,
    CheckmarkFilled,
    CheckmarkOutline,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleDash,
    CircleFill,
    CircleStroke,
    ColourPalette,
    Critical,
    CriticalSeverity,
    Dashboard,
    Database,
    DiamondFill,
    Edit,
    Enterprise,
    ErrorFilled,
    Group,
    Gui,
    HorizontalLineSolid,
    Incomplete,
    InformationFilled,
    InformationSquareFilled,
    InProgress,
    Launch,
    Login,
    LowSeverity,
    Menu,
    OverflowMenuVertical,
    Password,
    PageFirst,
    PageLast,
    PendingFilled,
    Save,
    Search,
    Settings,
    SquareFill,
    Subtract,
    Switcher,
    TrashCan,
    UndefinedFilled,
    UnknownFilled,
    Upgrade,
    User,
    UserAvatar,
    UserMultiple,
    UserProfile,
    UserRole,
    View,
    Warning,
    WarningAltFilled,
    WarningAltInvertedFilled,
    WarningFilled
}

public static class CarbonBlazorIconMapper
{
    public static string ToSvg(CarbonBlazorIcon icon, int sizeInPixels = 16, bool resizeViewBox = false) => 
        IconSvgTags.OpeningTag(sizeInPixels, resizeViewBox) 
        + icon switch
        {
            CarbonBlazorIcon.Add => IconSvgTags.Add,
            CarbonBlazorIcon.Apps => IconSvgTags.Apps,
            CarbonBlazorIcon.ArrowDownRight => IconSvgTags.ArrowDownRight,
            CarbonBlazorIcon.ArrowUpRight => IconSvgTags.ArrowUpRight,
            CarbonBlazorIcon.Building => IconSvgTags.Building,
            CarbonBlazorIcon.Calendar => IconSvgTags.Calendar,
            CarbonBlazorIcon.Cancel => IconSvgTags.Cancel,
            CarbonBlazorIcon.CaretDown => IconSvgTags.CaretDown,
            CarbonBlazorIcon.CaretUp => IconSvgTags.CaretUp,
            CarbonBlazorIcon.Caution => IconSvgTags.Caution,
            CarbonBlazorIcon.Checkmark => IconSvgTags.Checkmark,
            CarbonBlazorIcon.CheckmarkFilled => IconSvgTags.CheckmarkFilled,
            CarbonBlazorIcon.CheckmarkOutline => IconSvgTags.CheckmarkOutline,
            CarbonBlazorIcon.ChevronDown => IconSvgTags.ChevronDown,
            CarbonBlazorIcon.ChevronLeft => IconSvgTags.ChevronLeft,
            CarbonBlazorIcon.ChevronRight => IconSvgTags.ChevronRight,
            CarbonBlazorIcon.ChevronUp => IconSvgTags.ChevronUp,
            CarbonBlazorIcon.CircleDash => IconSvgTags.CircleDash,
            CarbonBlazorIcon.CircleFill => IconSvgTags.CircleFill,
            CarbonBlazorIcon.CircleStroke => IconSvgTags.CircleStroke,
            CarbonBlazorIcon.ColourPalette => IconSvgTags.ColourPalette,
            CarbonBlazorIcon.Critical => IconSvgTags.Critical,
            CarbonBlazorIcon.CriticalSeverity => IconSvgTags.CriticalSeverity,
            CarbonBlazorIcon.Dashboard => IconSvgTags.Dashboard,
            CarbonBlazorIcon.Database => IconSvgTags.Database,
            CarbonBlazorIcon.DiamondFill => IconSvgTags.DiamondFill,
            CarbonBlazorIcon.Edit => IconSvgTags.Edit,
            CarbonBlazorIcon.Enterprise => IconSvgTags.Enterprise,
            CarbonBlazorIcon.ErrorFilled => IconSvgTags.ErrorFilled,
            CarbonBlazorIcon.Group => IconSvgTags.Group,
            CarbonBlazorIcon.Gui => IconSvgTags.Gui,
            CarbonBlazorIcon.HorizontalLineSolid => IconSvgTags.HorizontalLineSolid,
            CarbonBlazorIcon.Incomplete => IconSvgTags.Incomplete,
            CarbonBlazorIcon.InformationFilled => IconSvgTags.InformationFilled,
            CarbonBlazorIcon.InformationSquareFilled => IconSvgTags.InformationSquareFilled,
            CarbonBlazorIcon.InProgress => IconSvgTags.InProgress,
            CarbonBlazorIcon.Launch => IconSvgTags.Launch,
            CarbonBlazorIcon.Login => IconSvgTags.Login,
            CarbonBlazorIcon.LowSeverity => IconSvgTags.LowSeverity,
            CarbonBlazorIcon.Menu => IconSvgTags.Menu,
            CarbonBlazorIcon.OverflowMenuVertical => IconSvgTags.OverflowMenuVertical,
            CarbonBlazorIcon.Password => IconSvgTags.Password,
            CarbonBlazorIcon.PageFirst => IconSvgTags.PageFirst,
            CarbonBlazorIcon.PageLast => IconSvgTags.PageLast,
            CarbonBlazorIcon.PendingFilled => IconSvgTags.PendingFilled,
            CarbonBlazorIcon.Save => IconSvgTags.Save,
            CarbonBlazorIcon.Search => IconSvgTags.Search,
            CarbonBlazorIcon.Settings => IconSvgTags.Settings,
            CarbonBlazorIcon.SquareFill => IconSvgTags.SquareFill,
            CarbonBlazorIcon.Subtract => IconSvgTags.Subtract,
            CarbonBlazorIcon.Switcher => IconSvgTags.Switcher,
            CarbonBlazorIcon.TrashCan => IconSvgTags.TrashCan,
            CarbonBlazorIcon.UndefinedFilled => IconSvgTags.UndefinedFilled,
            CarbonBlazorIcon.UnknownFilled => IconSvgTags.UnknownFilled,
            CarbonBlazorIcon.Upgrade => IconSvgTags.Upgrade,
            CarbonBlazorIcon.User => IconSvgTags.User,
            CarbonBlazorIcon.UserAvatar => IconSvgTags.UserAvatar,
            CarbonBlazorIcon.UserMultiple => IconSvgTags.UserMultiple,
            CarbonBlazorIcon.UserProfile => IconSvgTags.UserProfile,
            CarbonBlazorIcon.UserRole => IconSvgTags.UserRole,
            CarbonBlazorIcon.View => IconSvgTags.View,
            CarbonBlazorIcon.Warning => IconSvgTags.Warning,
            CarbonBlazorIcon.WarningAltFilled => IconSvgTags.WarningAltFilled,
            CarbonBlazorIcon.WarningAltInvertedFilled => IconSvgTags.WarningAltInvertedFilled,
            CarbonBlazorIcon.WarningFilled => IconSvgTags.WarningFilled,
            _ => string.Empty
        }
        + IconSvgTags.ClosingTag;
}
