name: BuildAndPack
on:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    
jobs:
  build-and-publish:
    permissions:
      contents: read  
      id-token: write  # enable GitHub OIDC token issuance for this job
      
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:AssemblyVersion=${VERSION} /p:Version=${VERSION}
        
      - name: Test
        run: dotnet test --configuration Release /p:AssemblyVersion=${VERSION} /p:Version=${VERSION} --no-build
          
      - name: Pack
        run: dotnet pack --configuration Release /p:AssemblyVersion=${VERSION} /p:Version=${VERSION} --no-build --output .
      
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{secrets.NUGET_USER}}
      
      # Push the package(s)
      - name: NuGet push
        run: dotnet nuget push Synonms.CarbonBlazor.${VERSION}.nupkg --api-key "${{steps.login.outputs.NUGET_API_KEY}}" --source https://api.nuget.org/v3/index.json
